version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: go
    volumes:
      - '.:/go/src/app:ro'
      - './data/:/go/src/app/data'
    working_dir: /go/src/app
    command: bash -c "go run *.go"
    ports:
      - '8080:8080'