version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: go
    volumes:
      - '.:/go/src/app:ro'
      - './vendor:/go/src/app/vendor'
    working_dir: /go/src/app
    command: bash -c "go run *.go"
    ports:
      - '8080:8080'
    links:
      - database:database
    environment:
      DATABASE_URL: "postgres://pqgouser@database:5432/gocrud_db?sslmode=disable"

  database:
    container_name: database
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile