version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: go
    volumes:
      - '.:/go/src/app:ro'
      - './vendor:/go/src/app/vendor'
      - './database:/go/src/app/database:ro'
    working_dir: /go/src/app
    command: bash -c "go run *.go"
    ports:
      - '8080:8080'
    links:
      - "database:database"

  database:
    image: mysql:5.7
    container_name: database
    command: '--init-file /go/src/app/database/init.sql'
    volumes:
      - './database/init.sql:/go/src/app/database/init.sql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: gocrud_db
      MYSQL_USER: simple_user
      MYSQL_PASSWORD: simple_user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

